### ISSUE TITLE
Unit-tests are crashing at import AzureMapsModule.

### ISSUE THREAD

**Issue by ganijon** [arnaudleclerc/ng-azure-maps#31]
I am following the readme of this repo. The application works Ok.
However, my unit-tests are crashing at import of the AzureMapsModule for the single reason, as highlighted:

  > nx run name-plate-app:test --testFile=app.component.spec
  [FAIL]  apps/nameplate/src/app/app.component.spec.ts
  ● Test suite failed to run

    TypeError: window.URL.createObjectURL is not a function

     import { ReactiveFormsModule } from '@angular/forms';
     import { AzureMapsModule } from 'ng-azure-maps';
     ^
     import { environment } from '../../environments/environment';
      
      at i (../../node_modules/azure-maps-control/dist/atlas.min.js:55:606)
      at ../../node_modules/azure-maps-control/dist/atlas.min.js:55:386100
      at e (../../node_modules/azure-maps-control/dist/atlas.min.js:55:376)
      at ../../node_modules/azure-maps-control/dist/atlas.min.js:55:420
      at ../../node_modules/azure-maps-control/dist/atlas.min.js:55:69
      at Object.<anonymous> (../../node_modules/azure-maps-control/dist/atlas.min.js:55:173)
      at ../../node_modules/ng-azure-maps/bundles/ng-azure-maps.umd.js:2:128
      at Object.<anonymous> (../../node_modules/ng-azure-maps/bundles/ng-azure-maps.umd.js:5:2)
      at Object.<anonymous> (src/app/nameplate/nameplate.module.ts:7:1)
      at Object.<anonymous> (src/app/app.component.spec.ts:4:1)

**Comment by ganijon** [comment]
For the failing tests, I tried window.URL.createObjectURL = jest.fn(). But, no luck. I investigated further in the package dependencies and found that my mono-repo based on Angular 10, and the latest version of ng-azure-maps depends on Angular 11. Looks likely that my next step will be investigating on the upgraded mono-repo to ng v.11.

**Comment by arnaudleclerc** [comment]
I doubt that this would be an angular version issue, but it is still worth the shot to try to upgrade it on your side. But I think your second approach would be more promising, trying to mock the `createObjectURL` function seems like something `jest` supports and recommends.

Maybe you can find your solution here : https://stackoverflow.com/questions/63052836/jest-typeerror-window-url-createobjecturl-is-not-a-function. The `atlas.js` library being based on `mapbox`, I would expect the issues to be quite similar.

I will try to take a deeper look at it whenever I find some time to do so, it may take a while though as I currently don't have a lot of time to work on this package.
